import Image from "next/image";
import Accordion from "./Accordion";

export const missions = [
  {
    title: "Profitability and Growth",
    content:
      "At Creon, we handpick cutting-edge AI projects and offer our community and token holders early access and investment opportunities. Our community actively contributes to the growth and profitability of these projects, creating a dynamic ecosystem of innovation and shared success.",
    imageUrl: "/mission1.svg",
  },
  {
    title: "Transparent & Fair Decentralized Earnings",

    content:
      "Creon is committed to maintaining a transparent and fair decentralized system where earnings are distributed equitably. Our platform ensures that all participants, from developers to token holders, have clear insights into financial operations and share in the profits generated by AI blockchain projects.",
    imageUrl: "/mission2.svg",
  },
  {
    title: "Launching the future",
    content:
      "Creon is spearheading the integration of AI and blockchain technologies to launch innovative projects that shape the future. Our initiatives are designed to leverage the strengths of both technologies, ensuring scalability, security, and efficiency in operations while fostering a new era of technological advancement.",
    imageUrl: "/mission3.svg",
  },
  {
    title: "Limitless Possibilities of AI & Crypto",
    content:
      "We believe in democratizing profits, ensuring that the benefits of our projects are shared fairly among all stakeholders.",
    imageUrl: "/mission4.svg",
  },
];

const OurMission = () => {
  return (
    <section className="w-full max-w-[1440px] mx-auto p-5 lg:px-32 2xl:px-0 mt-[100px]">
      <div className="flex flex-col justify-center items-center gap-10 md:flex-row md:items-start">
        <div className="w-full flex flex-col items-center gap-5">
          <h2 className="uppercase text-white font-MonumentExtended text-center xl:text-start text-xl md:text-3xl xl:text-[38px] max-w-[699px] leading-[120%]">
            OUR VISION IS TO SUPPORT THE INNOVATION OF AI BLOCKCHAIN PROJECTS {" "}
            <span className="custom-gradient-text">
              WHILE PRIORITIZING COMMUNITIES AND DEMOCRATIZING PROFITS
            </span>
          </h2>
          <Image
            src="/mission.png"
            alt="Our mission"
            width={800}
            height={500}
            className="w-full xl:mr-[-250px]"
          />
        </div>
        <div className="flex flex-col items-center h-full justify-start gap-[30px] max-w-[550px]">
          {missions.map((item, index) => (
            <Accordion
              key={index}
              title={item.title}
              content={item.content}
              imageUrl={item.imageUrl}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default OurMission;
